<list>
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv1" label="CCTV1综合" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv2" label="CCTV2财经" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv3" label="CCTV3综艺" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv4" label="CCTV4中文国际(亚洲)" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctveurope" label="CCTV4中文国际(欧洲)" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvamericas" label="CCTV4中文国际(美洲)" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv5" label="CCTV5体育" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvgaoqing" label="CCTV5+体育赛事" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv6" label="CCTV6电影" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv7" label="CCTV7军事农业" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv8" label="CCTV8电视剧" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvjilu" label="CCTV9纪录" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvdoc" label="CCTV9Documentary" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv10" label="CCTV10科教" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv11" label="CCTV11戏曲" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv12" label="CCTV12社会与法" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv13" label="CCTV13新闻" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctv9" label="CCTV-NEWS" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvchildren" label="CCTV14少儿" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvmusic" label="CCTV15音乐" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvxiyu" label="CCTV-E西语" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvfrance" label="CCTV-F法语" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvarabic" label="CCTV-A阿拉伯语" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=cctvrussian" label="CCTV-R俄语" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=btv1" label="北京卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=shanghai" label="东方卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=tianjin" label="天津卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=chongqing" label="重庆卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=heilongjiang" label="黑龙江卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=jilin" label="吉林卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=liaoning" label="辽宁卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=neimenggu" label="内蒙古卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=ningxia" label="宁夏卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=gansu" label="甘肃卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=qinghai" label="青海卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=shanxi2" label="陕西卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=hebei" label="河北卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=shanxi" label="山西卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=shandong" label="山东卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=anhui" label="安徽卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=henan" label="河南卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=hubei" label="湖北卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=jiangxi" label="江西卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=zhejiang" label="浙江卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=dongnan" label="东南卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=guangdong" label="广东卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=guangxi" label="广西卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=yunnan" label="云南卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=guizhou" label="贵州卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=sichuan" label="四川卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=xinjiang" label="新疆卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=xizang" label="西藏卫视" />
<m list_src="http://wltv.clanmark.com/php/cnhf.php?key=luyou" label="旅游卫视" />
</list>
