<?xml version="1.0" encoding="UTF-8" ?>
<list>
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv1" label="CCTV1综合" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv2" label="CCTV2财经" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv3" label="CCTV3综艺" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv4" label="CCTV4中文国际(亚洲)" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctveurope" label="CCTV4中文国际(欧洲)" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvamerica" label="CCTV4中文国际(美洲)" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv5" label="CCTV5体育" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv6" label="CCTV6电影" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv7" label="CCTV7军事农业" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv8" label="CCTV8电视剧" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvjilu" label="CCTV9纪录" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvdoc" label="CCTV9纪录(英)" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv10" label="CCTV10科教" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv11" label="CCTV11戏曲" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv12" label="CCTV12社会与法" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv13" label="CCTV13新闻" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvchild" label="CCTV14少儿" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvmusic" label="CCTV15音乐" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv9" label="CCTVNEWS" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvfrench" label="CCTV-F法语" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvxiyu" label="CCTV-E西语" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvarabic" label="CCTV-A阿语" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctvrussian" label="CCTV-R俄语" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=cctv5plus" label="CCTV5+体育赛事" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv1" label="北京卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=dongfang" label="东方卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=tianjin" label="天津卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=chongqing" label="重庆卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=heilongjiang" label="黑龙江卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=jilin" label="吉林卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=liaoning" label="辽宁卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=neimenggu" label="内蒙古卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=ningxia" label="宁夏卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=gansu" label="甘肃卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=qinghai" label="青海卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=shan3xi" label="陕西卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=hebei" label="河北卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=shan1xi" label="山西卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=shandong" label="山东卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=anhui" label="安徽卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=henan" label="河南卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=hubei" label="湖北卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=jiangxi" label="江西卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=zhejiang" label="浙江卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=dongnan" label="东南卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=xiamen" label="厦门卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=guangdong" label="广东卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=shenzhen" label="深圳卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=guangxi" label="广西卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=yunnan" label="云南卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=guizhou" label="贵州卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=sichuan" label="四川卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=xinjiang" label="新疆卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=xizang" label="西藏卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=travel" label="旅游卫视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv2" label="北京文艺" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv3" label="北京科教" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv4" label="北京影视" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv5" label="北京财经" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv6" label="北京体育" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv7" label="北京生活" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv8" label="北京青少" />
<m list_src="http://wltv.clanmark.com/php/cntvhf.php?vid=btv9" label="北京新闻" />
</list>